version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
      - api3

  api1:
    build: ./api
    hostname: api1
    expose:
      - "3000"
    depends_on:
      redis:
        condition: service_started
      haproxy:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=haproxy
      - POSTGRES_PORT=26256
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=""
      - POSTGRES_DB=appdb

  api2:
    build: ./api
    hostname: api2
    expose:
      - "3000"
    depends_on:
      redis:
        condition: service_started
      haproxy:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=haproxy
      - POSTGRES_PORT=26256
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=""
      - POSTGRES_DB=appdb

  api3:
    build: ./api
    hostname: api3
    expose:
      - "3000"
    depends_on:
      redis:
        condition: service_started
      haproxy:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=haproxy
      - POSTGRES_PORT=26256
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=""
      - POSTGRES_DB=appdb

  consumer1:
    build: ./consumer
    hostname: consumer1
    command: python consumer.py
    restart: on-failure
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      haproxy:
        condition: service_started
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=haproxy
      - POSTGRES_PORT=26256
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=""
      - POSTGRES_DB=appdb

  consumer2:
    build: ./consumer
    hostname: consumer2
    command: python consumer.py
    restart: on-failure
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      haproxy:
        condition: service_started
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=haproxy
      - POSTGRES_PORT=26256
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=""
      - POSTGRES_DB=appdb

  consumer3:
    build: ./consumer
    hostname: consumer3
    command: python consumer.py
    restart: on-failure
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      haproxy:
        condition: service_started
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=haproxy
      - POSTGRES_PORT=26256
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=""
      - POSTGRES_DB=appdb

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  crdb1:
    image: cockroachdb/cockroach:v23.1.11
    command: start --insecure --join=crdb1,crdb2,crdb3
    hostname: crdb1
    ports:
      - "26257:26257"
      - "18080:8080"
    volumes:
      - crdb1-data:/cockroach/cockroach-data

  crdb2:
    image: cockroachdb/cockroach:v23.1.11
    command: start --insecure --join=crdb1,crdb2,crdb3
    hostname: crdb2
    ports:
      - "26258:26257"
      - "18081:8080"
    volumes:
      - crdb2-data:/cockroach/cockroach-data

  crdb3:
    image: cockroachdb/cockroach:v23.1.11
    command: start --insecure --join=crdb1,crdb2,crdb3
    hostname: crdb3
    ports:
      - "26259:26257"
      - "18082:8080"
    volumes:
      - crdb3-data:/cockroach/cockroach-data

  crdb-init:
    image: cockroachdb/cockroach:v23.1.11
    depends_on:
      - crdb1
    entrypoint: >
      /bin/sh -c "
        echo 'Assuming crdb1 is ready...';
        echo 'Initializing cluster...';
        cockroach init --insecure --host=crdb1 || echo 'Already initialized';
        cockroach sql --insecure --host=crdb1 -e 'CREATE DATABASE appdb;'
        cockroach sql --insecure --host=crdb1 --database=appdb -e 'CREATE TABLE IF NOT EXISTS kv_store (key TEXT PRIMARY KEY,value TEXT,last_updated TIMESTAMPTZ NOT NULL DEFAULT NOW());'
        echo 'Done.';
      "

  haproxy:
    image: haproxy:2.9
    ports:
      - "26256:26256"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - crdb-init  # Ensure init happens first

  rabbitmq:
    image: rabbitmq:3-management
    container_name: golang-rabbitmq-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  crdb1-data:
  crdb2-data:
  crdb3-data:
